Layout/LineLength: # for Rubocop >= 0.78.0
  # This will disable the rule completely, regardless what other options you put
  Enabled: false
  # Change the default 80 chars limit value
  Max: 120
  # If you want the rule only apply to a specific folder/file
  Include:
    - 'app/**/*'
  # If you want the rule not to apply to a specific folder/file
  Exclude:
    - 'db/**/*'
    - 'db/migrate/**/*'
Metrics/MethodLength:
  Exclude:
    - 'db/**/*'
    - 'db/migrate/**/*'
Documentation:
  Enabled: false
AllCops:
  NewCops: enable
Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'test/**/*.rb'
    - 'spec/**/*.rb'
